/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import javax.swing.JOptionPane;
import nivel.avanzado;
import nivel.basico;
import nivel.intermedio;

/**
 *
 * @author Santiago
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcNivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        spJugadores = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡¡¡ Bienvenido !!!");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(143, 203, 217));
        jButton1.setText("Iniciar Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(0, 2));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Seleccione el nivel: ");
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2);

        jcNivel.setBackground(new java.awt.Color(143, 203, 217));
        jcNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basico", "Intermedio", "Avanzado" }));
        jPanel3.add(jcNivel);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Cantidad de jugadores: ");
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3);
        jPanel3.add(spJugadores);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int nivel = jcNivel.getSelectedIndex();
        int jugadores = (int) spJugadores.getValue();
        if (jugadores > 4 || jugadores < 2) {
            JOptionPane.showMessageDialog(this, "Debe elegir de 2 a 4 jugadores");
        } else if (nivel == 0) {
            this.dispose();
            basico ventana = new basico();
            if (jugadores == 2) {
                ventana.lblJugador3.setVisible(false);
                ventana.lblPuntaje3.setVisible(false);
                ventana.lblJugador4.setVisible(false);
                ventana.lblPuntaje4.setVisible(false);
            } else if (jugadores == 3) {
                ventana.lblJugador4.setVisible(false);
                ventana.lblPuntaje4.setVisible(false);
            }
            ventana.setVisible(true);
            ventana.lblJugadores.setText(jugadores+"");
        } else if (nivel == 1) {
            this.dispose();
            intermedio ventana = new intermedio();
            if (jugadores == 2) {
                ventana.lblJugador3.setVisible(false);
                ventana.lblPuntaje3.setVisible(false);
                ventana.lblJugador4.setVisible(false);
                ventana.lblPuntaje4.setVisible(false);
            } else if (jugadores == 3) {
                ventana.lblJugador4.setVisible(false);
                ventana.lblPuntaje4.setVisible(false);
            }
            ventana.setVisible(true);
            ventana.lblJugadores.setText(jugadores+"");
        } else if (nivel == 2) {
            this.dispose();
            avanzado ventana = new avanzado();
            if (jugadores == 2) {
                ventana.lblJugador3.setVisible(false);
                ventana.lblPuntaje3.setVisible(false);
                ventana.lblJugador4.setVisible(false);
                ventana.lblPuntaje4.setVisible(false);
            } else if (jugadores == 3) {
                ventana.lblJugador4.setVisible(false);
                ventana.lblPuntaje4.setVisible(false);
            }
            ventana.setVisible(true);
            ventana.lblJugadores.setText(jugadores+"");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcNivel;
    public static javax.swing.JSpinner spJugadores;
    // End of variables declaration//GEN-END:variables
}
