/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nivel;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Santi
 */
public class avanzado extends javax.swing.JFrame {

    int turno, jugador01, jugador02, jugador03, jugador04, jugadores,
            cont1, cont2, cont3, cont4;
    
    public avanzado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel01 = new javax.swing.JPanel();
        jPanel02 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblJugadores = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblPuntaje1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblPuntaje2 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblPuntaje3 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        lblPuntaje4 = new javax.swing.JLabel();
        jPanel03 = new javax.swing.JPanel();
        jpn9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpn10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpn11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpn12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jpn13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jpn14 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jpn8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpn33 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jpn34 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jpn35 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jpn36 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jpn15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jpn7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpn32 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jpn39 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jpn38 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jpn37 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jpn16 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jpn6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpn31 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jpn40 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpn17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jpn5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpn30 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jpn41 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jpn50 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpn18 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jpn4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jpn29 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jpn42 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jpn49 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jpn19 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jpn3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jpn28 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jpn43 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jpn48 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jpn47 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jpn20 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jpn2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jpn27 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jpn44 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jpn45 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jpn46 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jpn21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jpn1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jpn26 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpn25 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpn24 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpn23 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jpn22 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        inicio = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        carro1 = new javax.swing.JLabel();
        carro2 = new javax.swing.JLabel();
        carro3 = new javax.swing.JLabel();
        carro4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carrera Numerica");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel01.setLayout(new java.awt.BorderLayout());

        jPanel02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel02.setLayout(new java.awt.GridLayout(0, 2));

        jButton2.setBackground(new java.awt.Color(230, 126, 34));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Lanzar dados!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel02.add(jButton2);

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("0");
        jPanel02.add(lblResultado);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad de jugadores:");
        jPanel02.add(jLabel2);

        lblJugadores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadores.setText("0");
        jPanel02.add(lblJugadores);

        lblJugador1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador1.setText("Jugador 1:");
        jPanel02.add(lblJugador1);

        lblPuntaje1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje1.setText("0");
        jPanel02.add(lblPuntaje1);

        lblJugador2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador2.setText("Jugador 2:");
        jPanel02.add(lblJugador2);

        lblPuntaje2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje2.setText("0");
        jPanel02.add(lblPuntaje2);

        lblJugador3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador3.setText("Jugador 3:");
        jPanel02.add(lblJugador3);

        lblPuntaje3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje3.setText("0");
        jPanel02.add(lblPuntaje3);

        lblJugador4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador4.setText("Jugador 4:");
        jPanel02.add(lblJugador4);

        lblPuntaje4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje4.setText("0");
        jPanel02.add(lblPuntaje4);

        jPanel01.add(jPanel02, java.awt.BorderLayout.LINE_END);

        jPanel03.setLayout(new java.awt.GridLayout(0, 6));

        jpn9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jpn9.setLayout(new java.awt.GridLayout(0, 1));

        jLabel8.setBackground(new java.awt.Color(127, 140, 141));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("9");
        jLabel8.setOpaque(true);
        jpn9.add(jLabel8);

        jPanel03.add(jpn9);

        jpn10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn10.setLayout(new java.awt.GridLayout(0, 1));

        jLabel9.setBackground(new java.awt.Color(127, 140, 141));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("10");
        jLabel9.setOpaque(true);
        jpn10.add(jLabel9);

        jPanel03.add(jpn10);

        jpn11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn11.setLayout(new java.awt.GridLayout(0, 1));

        jLabel10.setBackground(new java.awt.Color(127, 140, 141));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("11");
        jLabel10.setOpaque(true);
        jpn11.add(jLabel10);

        jPanel03.add(jpn11);

        jpn12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn12.setLayout(new java.awt.GridLayout(0, 1));

        jLabel16.setBackground(new java.awt.Color(127, 140, 141));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llantas.jpg"))); // NOI18N
        jLabel16.setOpaque(true);
        jpn12.add(jLabel16);

        jPanel03.add(jpn12);

        jpn13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn13.setLayout(new java.awt.GridLayout(0, 1));

        jLabel22.setBackground(new java.awt.Color(127, 140, 141));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(236, 240, 241));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("13");
        jLabel22.setOpaque(true);
        jpn13.add(jLabel22);

        jPanel03.add(jpn13);

        jpn14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn14.setLayout(new java.awt.GridLayout(0, 1));

        jLabel28.setBackground(new java.awt.Color(127, 140, 141));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(236, 240, 241));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("14");
        jLabel28.setOpaque(true);
        jpn14.add(jLabel28);

        jPanel03.add(jpn14);

        jpn8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn8.setLayout(new java.awt.GridLayout(0, 1));

        jLabel7.setBackground(new java.awt.Color(127, 140, 141));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("8");
        jLabel7.setOpaque(true);
        jpn8.add(jLabel7);

        jPanel03.add(jpn8);

        jpn33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jpn33.setLayout(new java.awt.GridLayout(0, 1));

        jLabel25.setBackground(new java.awt.Color(127, 140, 141));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(236, 240, 241));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("33");
        jLabel25.setOpaque(true);
        jpn33.add(jLabel25);

        jPanel03.add(jpn33);

        jpn34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn34.setLayout(new java.awt.GridLayout(0, 1));

        jLabel26.setBackground(new java.awt.Color(127, 140, 141));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(236, 240, 241));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("34");
        jLabel26.setOpaque(true);
        jpn34.add(jLabel26);

        jPanel03.add(jpn34);

        jpn35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn35.setLayout(new java.awt.GridLayout(0, 1));

        jLabel31.setBackground(new java.awt.Color(127, 140, 141));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(236, 240, 241));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("35");
        jLabel31.setOpaque(true);
        jpn35.add(jLabel31);

        jPanel03.add(jpn35);

        jpn36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn36.setLayout(new java.awt.GridLayout(0, 1));

        jLabel32.setBackground(new java.awt.Color(127, 140, 141));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(236, 240, 241));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("36");
        jLabel32.setOpaque(true);
        jpn36.add(jLabel32);

        jPanel03.add(jpn36);

        jpn15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn15.setLayout(new java.awt.GridLayout(0, 1));

        jLabel37.setBackground(new java.awt.Color(127, 140, 141));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(236, 240, 241));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("15");
        jLabel37.setOpaque(true);
        jpn15.add(jLabel37);

        jPanel03.add(jpn15);

        jpn7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel6.setBackground(new java.awt.Color(127, 140, 141));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("7");
        jLabel6.setOpaque(true);
        jpn7.add(jLabel6);

        jPanel03.add(jpn7);

        jpn32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn32.setLayout(new java.awt.GridLayout(0, 1));

        jLabel20.setBackground(new java.awt.Color(127, 140, 141));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("32");
        jLabel20.setOpaque(true);
        jpn32.add(jLabel20);

        jPanel03.add(jpn32);

        jpn39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jpn39.setLayout(new java.awt.GridLayout(0, 1));

        jLabel36.setBackground(new java.awt.Color(127, 140, 141));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(236, 240, 241));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("39");
        jLabel36.setOpaque(true);
        jpn39.add(jLabel36);

        jPanel03.add(jpn39);

        jpn38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn38.setLayout(new java.awt.GridLayout(0, 1));

        jLabel34.setBackground(new java.awt.Color(127, 140, 141));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(236, 240, 241));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("38");
        jLabel34.setOpaque(true);
        jpn38.add(jLabel34);

        jPanel03.add(jpn38);

        jpn37.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jpn37.setLayout(new java.awt.GridLayout(0, 1));

        jLabel33.setBackground(new java.awt.Color(127, 140, 141));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(236, 240, 241));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("37");
        jLabel33.setOpaque(true);
        jpn37.add(jLabel33);

        jPanel03.add(jpn37);

        jpn16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn16.setLayout(new java.awt.GridLayout(0, 1));

        jLabel44.setBackground(new java.awt.Color(127, 140, 141));
        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(236, 240, 241));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("16");
        jLabel44.setOpaque(true);
        jpn16.add(jLabel44);

        jPanel03.add(jpn16);

        jpn6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn6.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setBackground(new java.awt.Color(127, 140, 141));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tacometro.jpg"))); // NOI18N
        jLabel5.setOpaque(true);
        jpn6.add(jLabel5);

        jPanel03.add(jpn6);

        jpn31.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn31.setLayout(new java.awt.GridLayout(0, 1));

        jLabel19.setBackground(new java.awt.Color(127, 140, 141));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("31");
        jLabel19.setOpaque(true);
        jpn31.add(jLabel19);

        jPanel03.add(jpn31);

        jpn40.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn40.setLayout(new java.awt.GridLayout(0, 1));

        jLabel38.setBackground(new java.awt.Color(127, 140, 141));
        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(236, 240, 241));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("40");
        jLabel38.setOpaque(true);
        jpn40.add(jLabel38);

        jPanel03.add(jpn40);

        jPanel1.setBackground(new java.awt.Color(39, 174, 96));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel03.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(39, 174, 96));
        jPanel2.setLayout(new java.awt.GridLayout());
        jPanel03.add(jPanel2);

        jpn17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn17.setLayout(new java.awt.GridLayout(0, 1));

        jLabel43.setBackground(new java.awt.Color(127, 140, 141));
        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(236, 240, 241));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("17");
        jLabel43.setOpaque(true);
        jpn17.add(jLabel43);

        jPanel03.add(jpn17);

        jpn5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel11.setBackground(new java.awt.Color(127, 140, 141));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("5");
        jLabel11.setOpaque(true);
        jpn5.add(jLabel11);

        jPanel03.add(jpn5);

        jpn30.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn30.setLayout(new java.awt.GridLayout(0, 1));

        jLabel35.setBackground(new java.awt.Color(127, 140, 141));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(236, 240, 241));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("30");
        jLabel35.setOpaque(true);
        jpn30.add(jLabel35);

        jPanel03.add(jpn30);

        jpn41.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn41.setLayout(new java.awt.GridLayout(0, 1));

        jLabel46.setBackground(new java.awt.Color(127, 140, 141));
        jLabel46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(236, 240, 241));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gasolina.jpg"))); // NOI18N
        jLabel46.setOpaque(true);
        jpn41.add(jLabel46);

        jPanel03.add(jpn41);

        jpn50.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn50.setLayout(new java.awt.GridLayout(0, 1));

        jLabel55.setBackground(new java.awt.Color(127, 140, 141));
        jLabel55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(236, 240, 241));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("50");
        jLabel55.setOpaque(true);
        jpn50.add(jLabel55);

        jPanel03.add(jpn50);

        jPanel3.setBackground(new java.awt.Color(39, 174, 96));
        jPanel3.setLayout(new java.awt.GridLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas.jpg"))); // NOI18N
        jPanel3.add(jLabel4);

        jPanel03.add(jPanel3);

        jpn18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn18.setLayout(new java.awt.GridLayout(0, 1));

        jLabel42.setBackground(new java.awt.Color(127, 140, 141));
        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(236, 240, 241));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("18");
        jLabel42.setOpaque(true);
        jpn18.add(jLabel42);

        jPanel03.add(jpn18);

        jpn4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn4.setLayout(new java.awt.GridLayout(0, 1));

        jLabel17.setBackground(new java.awt.Color(127, 140, 141));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("4");
        jLabel17.setOpaque(true);
        jpn4.add(jLabel17);

        jPanel03.add(jpn4);

        jpn29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn29.setLayout(new java.awt.GridLayout(0, 1));

        jLabel27.setBackground(new java.awt.Color(127, 140, 141));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(236, 240, 241));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("29");
        jLabel27.setOpaque(true);
        jpn29.add(jLabel27);

        jPanel03.add(jpn29);

        jpn42.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn42.setLayout(new java.awt.GridLayout(0, 1));

        jLabel47.setBackground(new java.awt.Color(127, 140, 141));
        jLabel47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(236, 240, 241));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("42");
        jLabel47.setOpaque(true);
        jpn42.add(jLabel47);

        jPanel03.add(jpn42);

        jpn49.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn49.setLayout(new java.awt.GridLayout(0, 1));

        jLabel54.setBackground(new java.awt.Color(127, 140, 141));
        jLabel54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(236, 240, 241));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("49");
        jLabel54.setOpaque(true);
        jpn49.add(jLabel54);

        jPanel03.add(jpn49);

        jPanel4.setBackground(new java.awt.Color(39, 174, 96));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel03.add(jPanel4);

        jpn19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn19.setLayout(new java.awt.GridLayout(0, 1));

        jLabel41.setBackground(new java.awt.Color(127, 140, 141));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(236, 240, 241));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("19");
        jLabel41.setOpaque(true);
        jpn19.add(jLabel41);

        jPanel03.add(jpn19);

        jpn3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel23.setBackground(new java.awt.Color(127, 140, 141));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(236, 240, 241));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("3");
        jLabel23.setOpaque(true);
        jpn3.add(jLabel23);

        jPanel03.add(jpn3);

        jpn28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn28.setLayout(new java.awt.GridLayout(0, 1));

        jLabel21.setBackground(new java.awt.Color(127, 140, 141));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("28");
        jLabel21.setOpaque(true);
        jpn28.add(jLabel21);

        jPanel03.add(jpn28);

        jpn43.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn43.setLayout(new java.awt.GridLayout(0, 1));

        jLabel48.setBackground(new java.awt.Color(127, 140, 141));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(236, 240, 241));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("43");
        jLabel48.setOpaque(true);
        jpn43.add(jLabel48);

        jPanel03.add(jpn43);

        jpn48.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn48.setLayout(new java.awt.GridLayout(0, 1));

        jLabel53.setBackground(new java.awt.Color(127, 140, 141));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(236, 240, 241));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("48");
        jLabel53.setOpaque(true);
        jpn48.add(jLabel53);

        jPanel03.add(jpn48);

        jpn47.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn47.setLayout(new java.awt.GridLayout(0, 1));

        jLabel52.setBackground(new java.awt.Color(127, 140, 141));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(236, 240, 241));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("47");
        jLabel52.setOpaque(true);
        jpn47.add(jLabel52);

        jPanel03.add(jpn47);

        jpn20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn20.setLayout(new java.awt.GridLayout(0, 1));

        jLabel40.setBackground(new java.awt.Color(127, 140, 141));
        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(236, 240, 241));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/garaje.JPG"))); // NOI18N
        jLabel40.setOpaque(true);
        jpn20.add(jLabel40);

        jPanel03.add(jpn20);

        jpn2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel29.setBackground(new java.awt.Color(127, 140, 141));
        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(236, 240, 241));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("2");
        jLabel29.setOpaque(true);
        jpn2.add(jLabel29);

        jPanel03.add(jpn2);

        jpn27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn27.setLayout(new java.awt.GridLayout(0, 1));

        jLabel15.setBackground(new java.awt.Color(127, 140, 141));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.JPG"))); // NOI18N
        jLabel15.setOpaque(true);
        jpn27.add(jLabel15);

        jPanel03.add(jpn27);

        jpn44.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn44.setLayout(new java.awt.GridLayout(0, 1));

        jLabel49.setBackground(new java.awt.Color(127, 140, 141));
        jLabel49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(236, 240, 241));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("44");
        jLabel49.setOpaque(true);
        jpn44.add(jLabel49);

        jPanel03.add(jpn44);

        jpn45.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn45.setLayout(new java.awt.GridLayout(0, 1));

        jLabel50.setBackground(new java.awt.Color(127, 140, 141));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(236, 240, 241));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("45");
        jLabel50.setOpaque(true);
        jpn45.add(jLabel50);

        jPanel03.add(jpn45);

        jpn46.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jpn46.setLayout(new java.awt.GridLayout(0, 1));

        jLabel51.setBackground(new java.awt.Color(127, 140, 141));
        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(236, 240, 241));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("46");
        jLabel51.setOpaque(true);
        jpn46.add(jLabel51);

        jPanel03.add(jpn46);

        jpn21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn21.setLayout(new java.awt.GridLayout(0, 1));

        jLabel30.setBackground(new java.awt.Color(127, 140, 141));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(236, 240, 241));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("21");
        jLabel30.setOpaque(true);
        jpn21.add(jLabel30);

        jPanel03.add(jpn21);

        jpn1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel39.setBackground(new java.awt.Color(127, 140, 141));
        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(236, 240, 241));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("1");
        jLabel39.setOpaque(true);
        jpn1.add(jLabel39);

        jPanel03.add(jpn1);

        jpn26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn26.setLayout(new java.awt.GridLayout(0, 1));

        jLabel14.setBackground(new java.awt.Color(127, 140, 141));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("26");
        jLabel14.setOpaque(true);
        jpn26.add(jLabel14);

        jPanel03.add(jpn26);

        jpn25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn25.setLayout(new java.awt.GridLayout(0, 1));

        jLabel13.setBackground(new java.awt.Color(127, 140, 141));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("25");
        jLabel13.setOpaque(true);
        jpn25.add(jLabel13);

        jPanel03.add(jpn25);

        jpn24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn24.setLayout(new java.awt.GridLayout(0, 1));

        jLabel12.setBackground(new java.awt.Color(127, 140, 141));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("24");
        jLabel12.setOpaque(true);
        jpn24.add(jLabel12);

        jPanel03.add(jpn24);

        jpn23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn23.setLayout(new java.awt.GridLayout(0, 1));

        jLabel18.setBackground(new java.awt.Color(127, 140, 141));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("23");
        jLabel18.setOpaque(true);
        jpn23.add(jLabel18);

        jPanel03.add(jpn23);

        jpn22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jpn22.setLayout(new java.awt.GridLayout(0, 1));

        jLabel24.setBackground(new java.awt.Color(127, 140, 141));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(236, 240, 241));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("22");
        jLabel24.setOpaque(true);
        jpn22.add(jLabel24);

        jPanel03.add(jpn22);

        inicio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        inicio.setLayout(new java.awt.GridLayout(0, 1));

        jLabel45.setBackground(new java.awt.Color(127, 140, 141));
        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(236, 240, 241));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Inicio");
        jLabel45.setOpaque(true);
        inicio.add(jLabel45);

        jPanel03.add(inicio);

        carro1.setBackground(new java.awt.Color(127, 140, 141));
        carro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro1.jpg"))); // NOI18N
        carro1.setOpaque(true);
        jPanel03.add(carro1);

        carro2.setBackground(new java.awt.Color(127, 140, 141));
        carro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro2.jpg"))); // NOI18N
        carro2.setOpaque(true);
        jPanel03.add(carro2);

        carro3.setBackground(new java.awt.Color(127, 140, 141));
        carro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro3.jpg"))); // NOI18N
        carro3.setOpaque(true);
        jPanel03.add(carro3);

        carro4.setBackground(new java.awt.Color(127, 140, 141));
        carro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro4.jpg"))); // NOI18N
        carro4.setOpaque(true);
        jPanel03.add(carro4);

        jPanel01.add(jPanel03, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel01, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void avanzar(int jugador, JLabel carro, JLabel posicion) {
        switch (jugador) {
            case 1:
                jpn1.add(carro);
                posicion.setText(jugador+"");
                break;
            case 2:
                jpn2.add(carro);
                posicion.setText(jugador+"");
                break;
            case 3:
                jpn3.add(carro);
                posicion.setText(jugador+"");
                break;
            case 4:
                jpn4.add(carro);
                posicion.setText(jugador+"");
                break;
            case 5:
                jpn5.add(carro);
                posicion.setText(jugador+"");
                break;
            case 6:
                jpn6.add(carro);
                posicion.setText(jugador+"");
                break;
            case 7:
                jpn7.add(carro);
                posicion.setText(jugador+"");
                break;
            case 8:
                jpn8.add(carro);
                posicion.setText(jugador+"");
                break;
            case 9:
                jpn9.add(carro);
                posicion.setText(jugador+"");
                break;
            case 10:
                jpn10.add(carro);
                posicion.setText(jugador+"");
                break;
            case 11:
                jpn11.add(carro);
                posicion.setText(jugador+"");
                break;
            case 12:
                jpn12.add(carro);
                posicion.setText(jugador+"");
                break;
            case 13:
                jpn13.add(carro);
                posicion.setText(jugador+"");
                break;
            case 14:
                jpn14.add(carro);
                posicion.setText(jugador+"");
                break;
            case 15:
                jpn15.add(carro);
                posicion.setText(jugador+"");
                break;
            case 16:
                jpn16.add(carro);
                posicion.setText(jugador+"");
                break;
            case 17:
                jpn17.add(carro);
                posicion.setText(jugador+"");
                break;
            case 18:
                jpn18.add(carro);
                posicion.setText(jugador+"");
                break;
            case 19:
                jpn19.add(carro);
                posicion.setText(jugador+"");
                break;
            case 20:
                jpn20.add(carro);
                posicion.setText(jugador+"");
                break;
            case 21:
                jpn21.add(carro);
                posicion.setText(jugador+"");
                break;
            case 22:
                jpn22.add(carro);
                posicion.setText(jugador+"");
                break;
            case 23:
                jpn23.add(carro);
                posicion.setText(jugador+"");
                break;
            case 24:
                jpn24.add(carro);
                posicion.setText(jugador+"");
                break;
            case 25:
                jpn25.add(carro);
                posicion.setText(jugador+"");
                break;
            case 26:
                jpn26.add(carro);
                posicion.setText(jugador+"");
                break;
            case 27:
                jpn27.add(carro);
                posicion.setText(jugador+"");
                break;
            case 28:
                jpn28.add(carro);
                posicion.setText(jugador+"");
                break;
            case 29:
                jpn29.add(carro);
                posicion.setText(jugador+"");
                break;
            case 30:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 31:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 32:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 33:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 34:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 35:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 36:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 37:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 38:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 39:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 40:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 41:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 42:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 43:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 44:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 45:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 46:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 47:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 48:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 49:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            case 50:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            default:
                break;
        }
    }
    
    public void proceso(int jugador, int resultado, JLabel carro, JLabel posicion, int pares) {
        if (jugador == 50) {
            avanzar(jugador, carro, posicion);
            JOptionPane.showMessageDialog(rootPane, "!! -- El jugador " + turno + " gana la partida -- !!");
            System.exit(0);
        } else if (pares == 3){
            JOptionPane.showMessageDialog(rootPane, "3 Pares consecutivos \n !! -- El jugador " + turno + " gana la partida -- !!");
            System.exit(0);
        } else if (jugador <= 50) {
            avanzar(jugador, carro, posicion);
            JOptionPane.showMessageDialog(rootPane, "El jugador " + turno + " avanza " + resultado + " Pasos");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setMinimumSize(new Dimension(800, 600));
        turno++;
        int cantidadJugadores = Integer.parseInt(lblJugadores.getText());

        double dado = Math.random() * 6 + 1;
        int resultado = (int) dado;
        lblResultado.setText(resultado + "");
        switch (turno) {
            case 1:
                if (resultado%2==0){
                    cont1++;
                } else {
                    cont1 = 0;
                }
                if ((jugador01 + resultado) <= 50) {
                    jugador01 = jugador01 + resultado;
                    proceso(jugador01, resultado, carro1, lblPuntaje1, cont1);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (50 - jugador01) + " Para ganar");
                }
                break;
            case 2:
                if (resultado%2==0){
                    cont2++;
                } else {
                    cont2 = 0;
                }
                if ((jugador02 + resultado) <= 50) {
                    jugador02 = jugador02 + resultado;
                    proceso(jugador02, resultado, carro2, lblPuntaje2, cont2);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (50 - jugador02) + " Para ganar");
                }
                break;
            case 3:
                if (resultado%2==0){
                    cont3++;
                } else {
                    cont3 = 0;
                }
                if ((jugador03 + resultado) <= 50) {
                    jugador03 = jugador03 + resultado;
                    proceso(jugador03, resultado, carro3, lblPuntaje3, cont3);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (50 - jugador03) + " Para ganar");
                }
                break;
            case 4:
                if (resultado%2==0){
                    cont4++;
                } else {
                    cont4 = 0;
                }
                if ((jugador04 + resultado) <= 50) {
                    jugador04 = jugador04 + resultado;
                    proceso(jugador04, resultado, carro4, lblPuntaje4, cont4);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (50 - jugador04) + " Para ganar");
                }
                break;
            default:
                break;
        }
        if (turno == cantidadJugadores) {
            turno = 0;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(avanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(avanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(avanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(avanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new avanzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carro1;
    private javax.swing.JLabel carro2;
    private javax.swing.JLabel carro3;
    private javax.swing.JLabel carro4;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel01;
    private javax.swing.JPanel jPanel02;
    private javax.swing.JPanel jPanel03;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn10;
    private javax.swing.JPanel jpn11;
    private javax.swing.JPanel jpn12;
    private javax.swing.JPanel jpn13;
    private javax.swing.JPanel jpn14;
    private javax.swing.JPanel jpn15;
    private javax.swing.JPanel jpn16;
    private javax.swing.JPanel jpn17;
    private javax.swing.JPanel jpn18;
    private javax.swing.JPanel jpn19;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn20;
    private javax.swing.JPanel jpn21;
    private javax.swing.JPanel jpn22;
    private javax.swing.JPanel jpn23;
    private javax.swing.JPanel jpn24;
    private javax.swing.JPanel jpn25;
    private javax.swing.JPanel jpn26;
    private javax.swing.JPanel jpn27;
    private javax.swing.JPanel jpn28;
    private javax.swing.JPanel jpn29;
    private javax.swing.JPanel jpn3;
    private javax.swing.JPanel jpn30;
    private javax.swing.JPanel jpn31;
    private javax.swing.JPanel jpn32;
    private javax.swing.JPanel jpn33;
    private javax.swing.JPanel jpn34;
    private javax.swing.JPanel jpn35;
    private javax.swing.JPanel jpn36;
    private javax.swing.JPanel jpn37;
    private javax.swing.JPanel jpn38;
    private javax.swing.JPanel jpn39;
    private javax.swing.JPanel jpn4;
    private javax.swing.JPanel jpn40;
    private javax.swing.JPanel jpn41;
    private javax.swing.JPanel jpn42;
    private javax.swing.JPanel jpn43;
    private javax.swing.JPanel jpn44;
    private javax.swing.JPanel jpn45;
    private javax.swing.JPanel jpn46;
    private javax.swing.JPanel jpn47;
    private javax.swing.JPanel jpn48;
    private javax.swing.JPanel jpn49;
    private javax.swing.JPanel jpn5;
    private javax.swing.JPanel jpn50;
    private javax.swing.JPanel jpn6;
    private javax.swing.JPanel jpn7;
    private javax.swing.JPanel jpn8;
    private javax.swing.JPanel jpn9;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    public javax.swing.JLabel lblJugador3;
    public javax.swing.JLabel lblJugador4;
    public javax.swing.JLabel lblJugadores;
    private javax.swing.JLabel lblPuntaje1;
    private javax.swing.JLabel lblPuntaje2;
    public javax.swing.JLabel lblPuntaje3;
    public javax.swing.JLabel lblPuntaje4;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
