/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nivel;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import ventana.ventana;

/**
 *
 * @author Santiago
 */
public class intermedio extends javax.swing.JFrame {

    int turno, jugador01, jugador02, jugador03, jugador04, jugadores,
            cont1, cont2, cont3, cont4;
    
    /**
     *
     */
    
    public intermedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel01 = new javax.swing.JPanel();
        jPanel02 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblJugadores = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblPuntaje1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblPuntaje2 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblPuntaje3 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        lblPuntaje4 = new javax.swing.JLabel();
        jPanel03 = new javax.swing.JPanel();
        jpn6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpn7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpn8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpn9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpn10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpn5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpn22 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jpn23 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jpn24 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpn11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpn4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jpn21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jpn30 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jpn25 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpn12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jpn3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jpn20 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jpn29 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jpn26 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpn13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jpn2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jpn19 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jpn28 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jpn27 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jpn14 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jpn1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jpn18 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jpn17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jpn16 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jpn15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        inicio = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        carro1 = new javax.swing.JLabel();
        carro2 = new javax.swing.JLabel();
        carro3 = new javax.swing.JLabel();
        carro4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carrera Numerica");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel01.setLayout(new java.awt.BorderLayout());

        jPanel02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel02.setLayout(new java.awt.GridLayout(0, 2));

        jButton2.setBackground(new java.awt.Color(230, 126, 34));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Lanzar dados!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel02.add(jButton2);

        lblResultado.setBackground(new java.awt.Color(0, 0, 0));
        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("0");
        jPanel02.add(lblResultado);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad de jugadores:");
        jPanel02.add(jLabel2);

        lblJugadores.setBackground(new java.awt.Color(0, 0, 0));
        lblJugadores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadores.setText("0");
        jPanel02.add(lblJugadores);

        lblJugador1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador1.setText("Jugador 1:");
        jPanel02.add(lblJugador1);

        lblPuntaje1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje1.setText("0");
        jPanel02.add(lblPuntaje1);

        lblJugador2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador2.setText("Jugador 2:");
        jPanel02.add(lblJugador2);

        lblPuntaje2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje2.setText("0");
        jPanel02.add(lblPuntaje2);

        lblJugador3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador3.setText("Jugador 3:");
        jPanel02.add(lblJugador3);

        lblPuntaje3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje3.setText("0");
        jPanel02.add(lblPuntaje3);

        lblJugador4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJugador4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJugador4.setText("Jugador 4:");
        jPanel02.add(lblJugador4);

        lblPuntaje4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPuntaje4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntaje4.setText("0");
        jPanel02.add(lblPuntaje4);

        jPanel01.add(jPanel02, java.awt.BorderLayout.LINE_END);

        jPanel03.setLayout(new java.awt.GridLayout(0, 5));

        jpn6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jpn6.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setBackground(new java.awt.Color(127, 140, 141));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("6");
        jLabel5.setOpaque(true);
        jpn6.add(jLabel5);

        jPanel03.add(jpn6);

        jpn7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel6.setBackground(new java.awt.Color(127, 140, 141));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("7");
        jLabel6.setOpaque(true);
        jpn7.add(jLabel6);

        jPanel03.add(jpn7);

        jpn8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn8.setLayout(new java.awt.GridLayout(0, 1));

        jLabel7.setBackground(new java.awt.Color(127, 140, 141));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("8");
        jLabel7.setOpaque(true);
        jpn8.add(jLabel7);

        jPanel03.add(jpn8);

        jpn9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn9.setLayout(new java.awt.GridLayout(0, 1));

        jLabel8.setBackground(new java.awt.Color(127, 140, 141));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llantas.jpg"))); // NOI18N
        jLabel8.setOpaque(true);
        jpn9.add(jLabel8);

        jPanel03.add(jpn9);

        jpn10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn10.setLayout(new java.awt.GridLayout(0, 1));

        jLabel9.setBackground(new java.awt.Color(127, 140, 141));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("10");
        jLabel9.setOpaque(true);
        jpn10.add(jLabel9);

        jPanel03.add(jpn10);

        jpn5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel11.setBackground(new java.awt.Color(127, 140, 141));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("5");
        jLabel11.setOpaque(true);
        jpn5.add(jLabel11);

        jPanel03.add(jpn5);

        jpn22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jpn22.setLayout(new java.awt.GridLayout(0, 1));

        jLabel24.setBackground(new java.awt.Color(127, 140, 141));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(236, 240, 241));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("22");
        jLabel24.setOpaque(true);
        jpn22.add(jLabel24);

        jPanel03.add(jpn22);

        jpn23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn23.setLayout(new java.awt.GridLayout(0, 1));

        jLabel18.setBackground(new java.awt.Color(127, 140, 141));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("23");
        jLabel18.setOpaque(true);
        jpn23.add(jLabel18);

        jPanel03.add(jpn23);

        jpn24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn24.setLayout(new java.awt.GridLayout(0, 1));

        jLabel12.setBackground(new java.awt.Color(127, 140, 141));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("24");
        jLabel12.setOpaque(true);
        jpn24.add(jLabel12);

        jPanel03.add(jpn24);

        jpn11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn11.setLayout(new java.awt.GridLayout(0, 1));

        jLabel10.setBackground(new java.awt.Color(127, 140, 141));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("11");
        jLabel10.setOpaque(true);
        jpn11.add(jLabel10);

        jPanel03.add(jpn11);

        jpn4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn4.setLayout(new java.awt.GridLayout(0, 1));

        jLabel17.setBackground(new java.awt.Color(127, 140, 141));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tacometro.jpg"))); // NOI18N
        jLabel17.setOpaque(true);
        jpn4.add(jLabel17);

        jPanel03.add(jpn4);

        jpn21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn21.setLayout(new java.awt.GridLayout(0, 1));

        jLabel30.setBackground(new java.awt.Color(127, 140, 141));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(236, 240, 241));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("21");
        jLabel30.setOpaque(true);
        jpn21.add(jLabel30);

        jPanel03.add(jpn21);

        jpn30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn30.setLayout(new java.awt.GridLayout(0, 1));

        jLabel35.setBackground(new java.awt.Color(127, 140, 141));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(236, 240, 241));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("30");
        jLabel35.setOpaque(true);
        jpn30.add(jLabel35);

        jPanel03.add(jpn30);

        jpn25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn25.setLayout(new java.awt.GridLayout(0, 1));

        jLabel13.setBackground(new java.awt.Color(127, 140, 141));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gasolina.jpg"))); // NOI18N
        jLabel13.setOpaque(true);
        jpn25.add(jLabel13);

        jPanel03.add(jpn25);

        jpn12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn12.setLayout(new java.awt.GridLayout(0, 1));

        jLabel16.setBackground(new java.awt.Color(127, 140, 141));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("12");
        jLabel16.setOpaque(true);
        jpn12.add(jLabel16);

        jPanel03.add(jpn12);

        jpn3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel23.setBackground(new java.awt.Color(127, 140, 141));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(236, 240, 241));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("3");
        jLabel23.setOpaque(true);
        jpn3.add(jLabel23);

        jPanel03.add(jpn3);

        jpn20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn20.setLayout(new java.awt.GridLayout(0, 1));

        jLabel40.setBackground(new java.awt.Color(127, 140, 141));
        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(236, 240, 241));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("20");
        jLabel40.setOpaque(true);
        jpn20.add(jLabel40);

        jPanel03.add(jpn20);

        jpn29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn29.setLayout(new java.awt.GridLayout(0, 1));

        jLabel27.setBackground(new java.awt.Color(127, 140, 141));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(236, 240, 241));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("29");
        jLabel27.setOpaque(true);
        jpn29.add(jLabel27);

        jPanel03.add(jpn29);

        jpn26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn26.setLayout(new java.awt.GridLayout(0, 1));

        jLabel14.setBackground(new java.awt.Color(127, 140, 141));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("26");
        jLabel14.setOpaque(true);
        jpn26.add(jLabel14);

        jPanel03.add(jpn26);

        jpn13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn13.setLayout(new java.awt.GridLayout(0, 1));

        jLabel22.setBackground(new java.awt.Color(127, 140, 141));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(236, 240, 241));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("13");
        jLabel22.setOpaque(true);
        jpn13.add(jLabel22);

        jPanel03.add(jpn13);

        jpn2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel29.setBackground(new java.awt.Color(127, 140, 141));
        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(236, 240, 241));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("2");
        jLabel29.setOpaque(true);
        jpn2.add(jLabel29);

        jPanel03.add(jpn2);

        jpn19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn19.setLayout(new java.awt.GridLayout(0, 1));

        jLabel41.setBackground(new java.awt.Color(127, 140, 141));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(236, 240, 241));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.JPG"))); // NOI18N
        jLabel41.setOpaque(true);
        jpn19.add(jLabel41);

        jPanel03.add(jpn19);

        jpn28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn28.setLayout(new java.awt.GridLayout(0, 1));

        jLabel21.setBackground(new java.awt.Color(127, 140, 141));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("28");
        jLabel21.setOpaque(true);
        jpn28.add(jLabel21);

        jPanel03.add(jpn28);

        jpn27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jpn27.setLayout(new java.awt.GridLayout(0, 1));

        jLabel15.setBackground(new java.awt.Color(127, 140, 141));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("27");
        jLabel15.setOpaque(true);
        jpn27.add(jLabel15);

        jPanel03.add(jpn27);

        jpn14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn14.setLayout(new java.awt.GridLayout(0, 1));

        jLabel28.setBackground(new java.awt.Color(127, 140, 141));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(236, 240, 241));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/garaje.JPG"))); // NOI18N
        jLabel28.setOpaque(true);
        jpn14.add(jLabel28);

        jPanel03.add(jpn14);

        jpn1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jpn1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel39.setBackground(new java.awt.Color(127, 140, 141));
        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(236, 240, 241));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("1");
        jLabel39.setOpaque(true);
        jpn1.add(jLabel39);

        jPanel03.add(jpn1);

        jpn18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn18.setLayout(new java.awt.GridLayout(0, 1));

        jLabel42.setBackground(new java.awt.Color(127, 140, 141));
        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(236, 240, 241));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("18");
        jLabel42.setOpaque(true);
        jpn18.add(jLabel42);

        jPanel03.add(jpn18);

        jpn17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn17.setLayout(new java.awt.GridLayout(0, 1));

        jLabel43.setBackground(new java.awt.Color(127, 140, 141));
        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(236, 240, 241));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("17");
        jLabel43.setOpaque(true);
        jpn17.add(jLabel43);

        jPanel03.add(jpn17);

        jpn16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpn16.setLayout(new java.awt.GridLayout(0, 1));

        jLabel44.setBackground(new java.awt.Color(127, 140, 141));
        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(236, 240, 241));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("16");
        jLabel44.setOpaque(true);
        jpn16.add(jLabel44);

        jPanel03.add(jpn16);

        jpn15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jpn15.setLayout(new java.awt.GridLayout(0, 1));

        jLabel37.setBackground(new java.awt.Color(127, 140, 141));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(236, 240, 241));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("15");
        jLabel37.setOpaque(true);
        jpn15.add(jLabel37);

        jPanel03.add(jpn15);

        inicio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        inicio.setLayout(new java.awt.GridLayout(0, 1));

        jLabel45.setBackground(new java.awt.Color(127, 140, 141));
        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(236, 240, 241));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Inicio");
        jLabel45.setOpaque(true);
        inicio.add(jLabel45);

        jPanel03.add(inicio);

        carro1.setBackground(new java.awt.Color(127, 140, 141));
        carro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro1.jpg"))); // NOI18N
        carro1.setOpaque(true);
        jPanel03.add(carro1);

        carro2.setBackground(new java.awt.Color(127, 140, 141));
        carro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro2.jpg"))); // NOI18N
        carro2.setOpaque(true);
        jPanel03.add(carro2);

        carro3.setBackground(new java.awt.Color(127, 140, 141));
        carro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro3.jpg"))); // NOI18N
        carro3.setOpaque(true);
        jPanel03.add(carro3);

        carro4.setBackground(new java.awt.Color(127, 140, 141));
        carro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro4.jpg"))); // NOI18N
        carro4.setOpaque(true);
        jPanel03.add(carro4);

        jPanel01.add(jPanel03, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel01, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void avanzar(int jugador, JLabel carro, JLabel posicion) {
        switch (jugador) {
            case 1:
                jpn1.add(carro);
                posicion.setText(jugador+"");
                break;
            case 2:
                jpn2.add(carro);
                posicion.setText(jugador+"");
                break;
            case 3:
                jpn3.add(carro);
                posicion.setText(jugador+"");
                break;
            case 4:
                jpn4.add(carro);
                posicion.setText(jugador+"");
                break;
            case 5:
                jpn5.add(carro);
                posicion.setText(jugador+"");
                break;
            case 6:
                jpn6.add(carro);
                posicion.setText(jugador+"");
                break;
            case 7:
                jpn7.add(carro);
                posicion.setText(jugador+"");
                break;
            case 8:
                jpn8.add(carro);
                posicion.setText(jugador+"");
                break;
            case 9:
                jpn9.add(carro);
                posicion.setText(jugador+"");
                break;
            case 10:
                jpn10.add(carro);
                posicion.setText(jugador+"");
                break;
            case 11:
                jpn11.add(carro);
                posicion.setText(jugador+"");
                break;
            case 12:
                jpn12.add(carro);
                posicion.setText(jugador+"");
                break;
            case 13:
                jpn13.add(carro);
                posicion.setText(jugador+"");
                break;
            case 14:
                jpn14.add(carro);
                posicion.setText(jugador+"");
                break;
            case 15:
                jpn15.add(carro);
                posicion.setText(jugador+"");
                break;
            case 16:
                jpn16.add(carro);
                posicion.setText(jugador+"");
                break;
            case 17:
                jpn17.add(carro);
                posicion.setText(jugador+"");
                break;
            case 18:
                jpn18.add(carro);
                posicion.setText(jugador+"");
                break;
            case 19:
                jpn19.add(carro);
                posicion.setText(jugador+"");
                break;
            case 20:
                jpn20.add(carro);
                posicion.setText(jugador+"");
                break;
            case 21:
                jpn21.add(carro);
                posicion.setText(jugador+"");
                break;
            case 22:
                jpn22.add(carro);
                posicion.setText(jugador+"");
                break;
            case 23:
                jpn23.add(carro);
                posicion.setText(jugador+"");
                break;
            case 24:
                jpn24.add(carro);
                posicion.setText(jugador+"");
                break;
            case 25:
                jpn25.add(carro);
                posicion.setText(jugador+"");
                break;
            case 26:
                jpn26.add(carro);
                posicion.setText(jugador+"");
                break;
            case 27:
                jpn27.add(carro);
                posicion.setText(jugador+"");
                break;
            case 28:
                jpn28.add(carro);
                posicion.setText(jugador+"");
                break;
            case 29:
                jpn29.add(carro);
                posicion.setText(jugador+"");
                break;
            case 30:
                jpn30.add(carro);
                posicion.setText(jugador+"");
                break;
            default:
                break;
        }
    }
    
    public void proceso(int jugador, int resultado, JLabel carro, JLabel posicion, int pares) {
        if (jugador == 30) {
            avanzar(jugador, carro, posicion);
            JOptionPane.showMessageDialog(rootPane, "!! -- El jugador " + turno + " gana la partida -- !!");
            System.exit(0);
        } else if (pares == 3){
            JOptionPane.showMessageDialog(rootPane, "3 Pares consecutivos \n !! -- El jugador " + turno + " gana la partida -- !!");
            System.exit(0);
        } else if (jugador <= 30) {
            avanzar(jugador, carro, posicion);
            JOptionPane.showMessageDialog(rootPane, "El jugador " + turno + " avanza " + resultado + " Pasos");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setMinimumSize(new Dimension(800, 600));
        turno++;
        int cantidadJugadores = Integer.parseInt(lblJugadores.getText());

        double dado = Math.random() * 6 + 1;
        int resultado = (int) dado;
        lblResultado.setText(resultado + "");
        switch (turno) {
            case 1:
                if (resultado%2==0){
                    cont1++;
                } else {
                    cont1 = 0;
                }
                if ((jugador01 + resultado) <= 30) {
                    jugador01 = jugador01 + resultado;
                    proceso(jugador01, resultado, carro1, lblPuntaje1, cont1);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (30 - jugador01) + " Para ganar");
                }
                break;
            case 2:
                if (resultado%2==0){
                    cont2++;
                } else {
                    cont2 = 0;
                }
                if ((jugador02 + resultado) <= 30) {
                    jugador02 = jugador02 + resultado;
                    proceso(jugador02, resultado, carro2, lblPuntaje2, cont2);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (30 - jugador02) + " Para ganar");
                }
                break;
            case 3:
                if (resultado%2==0){
                    cont3++;
                } else {
                    cont3 = 0;
                }
                if ((jugador03 + resultado) <= 30) {
                    jugador03 = jugador03 + resultado;
                    proceso(jugador03, resultado, carro3, lblPuntaje3, cont3);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (30 - jugador03) + " Para ganar");
                }
                break;
            case 4:
                if (resultado%2==0){
                    cont4++;
                } else {
                    cont4 = 0;
                }
                if ((jugador04 + resultado) <= 30) {
                    jugador04 = jugador04 + resultado;
                    proceso(jugador04, resultado, carro4, lblPuntaje4, cont4);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Resultado: " + resultado + "\nEl jugador " + turno + " no avanza " + "\nNecesita " + (30 - jugador04) + " Para ganar");
                }
                break;
            default:
                break;
        }
        if (turno == cantidadJugadores) {
            turno = 0;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intermedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carro1;
    private javax.swing.JLabel carro2;
    private javax.swing.JLabel carro3;
    private javax.swing.JLabel carro4;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel01;
    private javax.swing.JPanel jPanel02;
    private javax.swing.JPanel jPanel03;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn10;
    private javax.swing.JPanel jpn11;
    private javax.swing.JPanel jpn12;
    private javax.swing.JPanel jpn13;
    private javax.swing.JPanel jpn14;
    private javax.swing.JPanel jpn15;
    private javax.swing.JPanel jpn16;
    private javax.swing.JPanel jpn17;
    private javax.swing.JPanel jpn18;
    private javax.swing.JPanel jpn19;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn20;
    private javax.swing.JPanel jpn21;
    private javax.swing.JPanel jpn22;
    private javax.swing.JPanel jpn23;
    private javax.swing.JPanel jpn24;
    private javax.swing.JPanel jpn25;
    private javax.swing.JPanel jpn26;
    private javax.swing.JPanel jpn27;
    private javax.swing.JPanel jpn28;
    private javax.swing.JPanel jpn29;
    private javax.swing.JPanel jpn3;
    private javax.swing.JPanel jpn30;
    private javax.swing.JPanel jpn4;
    private javax.swing.JPanel jpn5;
    private javax.swing.JPanel jpn6;
    private javax.swing.JPanel jpn7;
    private javax.swing.JPanel jpn8;
    private javax.swing.JPanel jpn9;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    public javax.swing.JLabel lblJugador3;
    public javax.swing.JLabel lblJugador4;
    public javax.swing.JLabel lblJugadores;
    private javax.swing.JLabel lblPuntaje1;
    private javax.swing.JLabel lblPuntaje2;
    public javax.swing.JLabel lblPuntaje3;
    public javax.swing.JLabel lblPuntaje4;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
